export const {
  // B
  BACKEND_LOCALHOST_URL,
  BACKEND_PRODUCTION_URL,

  // C
  CLOUDINARY_IMAGE_CLOUD_NAME,
  CLOUDINARY_IMAGE_API_KEY,
  CLOUDINARY_IMAGE_API_SECRET,
  CLOUDINARY_MAIN_FOLDER,
  CLOUDINARY_PRODUCT_CLOUD_NAME,
  CLOUDINARY_PRODUCT_API_KEY,
  CLOUDINARY_PRODUCT_API_SECRET,
  CLOUDINARY_VIDEO_CLOUD_NAME,
  CLOUDINARY_VIDEO_API_KEY,
  CLOUDINARY_VIDEO_API_SECRET,

  // F
  FRONTEND_LOCAL_HOST_CLIENT_URL,
  FRONTEND_LOCAL_HOST_ADMIN_URL,
  FRONTEND_LOCAL_HOST_MASTER_URL,
  FRONTEND_LOCAL_HOST_PUBLIC_URL_1,
  FRONTEND_LOCAL_HOST_PUBLIC_URL_2,
  FRONTEND_PRODUCTION_CLIENT_URL,
  FRONTEND_PRODUCTION_ADMIN_URL,
  FRONTEND_PRODUCTION_MASTER_URL,

  // G
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  GITHUB_REDIRECT_ENDPOINT,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_ENDPOINT,

  // J
  JWT_SECRET,

  // L
  LINKEDIN_CLIENT_ID,
  LINKEDIN_CLIENT_SECRET,
  LINKEDIN_REDIRECT_ENDPOINT,

  // M
  MAIL_SERVICE_DEVELOPMENT_BASE_URL,
  MAIL_SERVICE_PRODUCTION_BASE_URL,
  MISTRAL_API_KEY, // Mistral automatically read it with this name only don't change it
  MISTRAL_API_KEY_POST,
  MISTRAL_API_KEY_GET,
  MONGODB_URI,

  // N
  IS_DEV,

  // P
  PORT,

  // R
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
  RAZORPAY_WEBHOOK_SECRET,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  REDIS_USERNAME,
}: NodeJS.ProcessEnv = process.env;

export const IS_DEV_MODE = IS_DEV === "true";
